"""
Canonical symbol → CoinGecko ID mapping. Single source of truth.

All backend modules and the frontend (via /api/config) should use this mapping
instead of maintaining their own copies.
"""

SYMBOL_TO_COINGECKO: dict[str, str] = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "SOL": "solana",
    "BNB": "binancecoin",
    "XRP": "ripple",
    "ADA": "cardano",
    "AVAX": "avalanche-2",
    "LINK": "chainlink",
    "DOT": "polkadot",
    "PEPE": "pepe",
    "DOGE": "dogecoin",
    "SHIB": "shiba-inu",
    "UNI": "uniswap",
    "AAVE": "aave",
    "MATIC": "matic-network",
    "POL": "polygon-ecosystem-token",
    "LTC": "litecoin",
    "ATOM": "cosmos",
    "XLM": "stellar",
    "BCH": "bitcoin-cash",
    "NEAR": "near",
    "APE": "apecoin",
    "FIL": "filecoin",
    "ARB": "arbitrum",
    "OP": "optimism",
    "INJ": "injective-protocol",
    "SUI": "sui",
    "SEI": "sei-network",
    "STX": "blockstack",
    "TIA": "celestia",
    "RUNE": "thorchain",
    "TRX": "tron",
    "APT": "aptos",
    "ETC": "ethereum-classic",
    "WLD": "worldcoin-wld",
    "FET": "fetch-ai",
    "JUP": "jupiter-exchange-solana",
    "ORDI": "ordinals",
    "PENDLE": "pendle",
    "STRK": "starknet",
    "EIGEN": "eigenlayer",
    "IMX": "immutable-x",
    "RENDER": "render-token",
    "GRT": "the-graph",
    "SAND": "the-sandbox",
    "MANA": "decentraland",
    "AXS": "axie-infinity",
    "GMT": "stepn",
    "CRV": "curve-dao-token",
    "MKR": "maker",
    "COMP": "compound-governance-token",
    "SNX": "havven",
    "LDO": "lido-dao",
    "ENS": "ethereum-name-service",
    "GMX": "gmx",
    "MAGIC": "magic",
    "BONK": "bonk",
    "FLOKI": "floki",
    "WIF": "dogwifcoin",
    "MEME": "memecoin",
    "1000PEPE": "1000pepe",
    "1000SATS": "1000sats-ordinals",
    "1000BONK": "1000bonk",
    "PYTH": "pyth-network",
    "JTO": "jito-governance-token",
    "DYM": "dymension",
    "TAO": "bittensor",
    "JASMY": "jasmycoin",
    "ZRO": "layerzero",
    "ENA": "ethena",
    "EDU": "edu-coin",
    "BLUR": "blur",
    "ID": "spaceland",
    "RDNT": "radiant-capital",
    "CFX": "conflux-token",
    "CORE": "core-dao",
    "MASK": "mask-network",
    "SKL": "skale",
    "MINA": "mina-protocol",
    "ASTR": "astar",
    "KAVA": "kava",
    "ONE": "harmony",
    "FTM": "fantom",
    "CELO": "celo",
    "KSM": "kusama",
    "ZIL": "zilliqa",
    "THETA": "theta-token",
    "SUSHI": "sushi",
    "1INCH": "1inch",
    "YFI": "yearn-finance",
    "USDC": "usd-coin",
}


def get_coingecko_id(symbol: str) -> str | None:
    """Resolve a coin symbol to its CoinGecko API id."""
    return SYMBOL_TO_COINGECKO.get(symbol.upper())
