"""
Trading presets inspired by the world's top 100 traders and institutional strategies.

Covers legendary traders, hedge fund managers, quant pioneers, macro traders,
crypto-native strategists, and modern systematic approaches. Each preset defines
SL/TP ATR multipliers per regime (ranging, trending, chaotic).
Values are MINIMUMS—the bot widens AI suggestions if they fall below these.
"""

# Format: (min_sl_atr, min_tp_atr) per regime -> (ranging, trending, chaotic)
# min_rr = minimum reward:risk ratio

PRESETS = {
    # ── GENERAL / DEFAULT ──────────────────────────────────────────────────
    "default": {
        "name": "Default (Balanced)",
        "trader": "Bot default",
        "description": "Moderate risk, 1.5–2:1 R:R. General-purpose crypto swing.",
        "ranging": {"sl": 1.2, "tp": 2.0},
        "trending": {"sl": 1.5, "tp": 2.5},
        "chaotic": {"sl": 2.0, "tp": 3.0},
        "min_rr": 1.5,
        "ai_guidance": "TP at 2.5–4x ATR, SL at 1.5–2.5x ATR.",
    },
    # ── TREND FOLLOWERS ────────────────────────────────────────────────────
    "turtle": {
        "name": "Turtle Traders",
        "trader": "Richard Dennis",
        "description": "2N (2×ATR) stops, mechanical trend-following. Max 2% risk/trade.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL at 2×ATR. TP at 4×ATR. Mechanical trend follow—let winners run.",
    },
    "seykota": {
        "name": "Ed Seykota",
        "trader": "Ed Seykota",
        "description": "ATR position sizing. 1% risk. Trailing stops where chart sours.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2–2.5×ATR. Let winners run with trailing stops. Risk 1% per trade.",
    },
    "trend_dunn": {
        "name": "Dunn Capital Trend",
        "trader": "Bill Dunn",
        "description": "Pure long-term trend following. Wide stops, huge runners. 20+ year track record.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 6.0},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2.5×ATR. Pure trend follow—ignore noise, ride the trend. Only exit on trend reversal.",
    },
    "trend_henry": {
        "name": "John W. Henry",
        "trader": "John W. Henry",
        "description": "Systematic long-term trend following. Patience through drawdowns.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 5.5},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2.5×ATR. Long-term trend capture. Accept drawdowns, never abandon the system.",
    },
    "trend_harding": {
        "name": "Winton Trend",
        "trader": "David Harding",
        "description": "Statistical trend following. Data-driven entries. Diversified systematic.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Statistical edge—follow the data, not the narrative. Diversify entries.",
    },
    "trend_abraham": {
        "name": "Abraham Trading",
        "trader": "Salem Abraham",
        "description": "Mechanical trend following from Texas. Simple rules, iron discipline.",
        "ranging": {"sl": 2.0, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 2–2.5×ATR. Mechanical rules only. No discretion. Let the system work.",
    },
    "trend_millburn": {
        "name": "Millburn Ridgefield",
        "trader": "Millburn Ridgefield",
        "description": "Multi-strategy CTA. Trend + mean-reversion blend. Institutional grade.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.7,
        "ai_guidance": "SL 2×ATR. Blend trend and mean-reversion signals. Adapt to regime.",
    },
    # ── MACRO TRADERS ──────────────────────────────────────────────────────
    "soros": {
        "name": "Soros Reflexivity",
        "trader": "George Soros",
        "description": "Always has SL. Decisive macro bets. Asymmetric when right.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "Never enter without defined SL. TP 2–3× risk. Cut losers, press winners.",
    },
    "ptj": {
        "name": "Paul Tudor Jones",
        "trader": "Paul Tudor Jones",
        "description": "Great defense > offense. Mental stops. Assume every position is wrong.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR minimum. Capital preservation first. Time stops if trade stalls.",
    },
    "druckenmiller": {
        "name": "Druckenmiller Macro",
        "trader": "Stanley Druckenmiller",
        "description": "Cut fast when wrong. Press hard when right. Concentrated conviction.",
        "ranging": {"sl": 1.8, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.0, "tp": 4.5},
        "min_rr": 2.0,
        "ai_guidance": "Cut losers fast. TP 2–2.5× SL when thesis confirms. Asymmetric sizing.",
    },
    "kovner": {
        "name": "Kovner Conservative",
        "trader": "Bruce Kovner",
        "description": "Undertrade. Volatility-adjusted. Preserve capital first.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.5, "tp": 4.5},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.5,
        "ai_guidance": "Wide SL (2–3×ATR). Avoid overtrading. Preserve capital.",
    },
    "bacon": {
        "name": "Louis Bacon Macro",
        "trader": "Louis Bacon",
        "description": "Macro conviction with tight risk. Moore Capital style—cut and re-enter.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.8–2×ATR. Macro thesis driven. Cut and re-enter rather than hold through pain.",
    },
    "dalio": {
        "name": "Dalio All-Weather",
        "trader": "Ray Dalio",
        "description": "Risk parity principles. Balance risk across regimes. Systematic macro.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Balance risk across conditions. Diversify. Reduce position in chaos.",
    },
    "robertson": {
        "name": "Julian Robertson",
        "trader": "Julian Robertson",
        "description": "Tiger Management style. Deep fundamental conviction. Concentrated bets.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. High-conviction entries only. Concentrate when thesis is strong.",
    },
    "steinhardt": {
        "name": "Michael Steinhardt",
        "trader": "Michael Steinhardt",
        "description": "Variant perception. Contrarian when data supports. Aggressive when right.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Trade variant perception—where your view differs from consensus with evidence.",
    },
    "tudor_bvi": {
        "name": "Tudor BVI Macro",
        "trader": "Tudor Investment Corp",
        "description": "Multi-manager macro. Blend discretionary + systematic. Risk budgeted.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Multi-signal approach. Risk budget per trade. Cut at -1.5% portfolio impact.",
    },
    # ── STOCK MARKET LEGENDS ───────────────────────────────────────────────
    "livermore": {
        "name": "Livermore Pivots",
        "trader": "Jesse Livermore",
        "description": "Cut at pivot failure. Pyramid into winners. Never average down.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 1.8, "tp": 3.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 1.8,
        "ai_guidance": "SL at pivot invalidation (~1.5–2×ATR). Add to winners only. Cut fast when wrong.",
    },
    "minervini": {
        "name": "Minervini Momentum",
        "trader": "Mark Minervini",
        "description": "7–8% stop, let winners run 20–30%. Risk management over win rate.",
        "ranging": {"sl": 2.0, "tp": 4.5},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.2,
        "ai_guidance": "SL ~2×ATR. TP 2.2–2.5× risk. Let winners run. Cut losers at 7–8% equivalent.",
    },
    "oneil": {
        "name": "William O'Neil CANSLIM",
        "trader": "William O'Neil",
        "description": "CANSLIM growth momentum. Buy breakouts, cut at 7–8%. IBD methodology.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL ~1.5–2×ATR (7–8% max loss). Buy breakouts from consolidation. Sell into strength at 20–25%.",
    },
    "darvas": {
        "name": "Nicolas Darvas Box",
        "trader": "Nicolas Darvas",
        "description": "Box breakout system. Buy new highs, stop below box floor.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 1.8, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 1.8,
        "ai_guidance": "SL below consolidation box (~1.5–2×ATR). Buy breakouts to new highs. Trail stop to new box floors.",
    },
    "zanger": {
        "name": "Dan Zanger Breakout",
        "trader": "Dan Zanger",
        "description": "Chart pattern breakouts with massive volume. World record returns.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 1.8, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Only enter on volume breakouts from clear patterns. No volume = no trade.",
    },
    "weinstein": {
        "name": "Weinstein Stage",
        "trader": "Stan Weinstein",
        "description": "Stage analysis. Buy Stage 2 breakouts, avoid Stage 3/4. 30-week MA.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR below breakout. Only buy in Stage 2 (above rising 30-period MA). Avoid Stage 4 shorts in uptrends.",
    },
    "lefevre": {
        "name": "Reminiscences Classic",
        "trader": "Edwin Lefèvre / Livermore",
        "description": "Classic tape reading. Wait for the market to confirm. Patience is profit.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR. Wait for confirmation before entry. The big money is in the waiting.",
    },
    # ── QUANTITATIVE / SYSTEMATIC ─────────────────────────────────────────
    "simons": {
        "name": "Renaissance Quant",
        "trader": "Jim Simons",
        "description": "Statistical arbitrage. High-frequency signals. Medallion-inspired edge.",
        "ranging": {"sl": 1.0, "tp": 2.0},
        "trending": {"sl": 1.2, "tp": 2.5},
        "chaotic": {"sl": 1.5, "tp": 2.5},
        "min_rr": 1.5,
        "ai_guidance": "Tight SL 1–1.5×ATR. High win rate, small edge per trade. Statistical signals only. No narrative.",
    },
    "shannon": {
        "name": "Shannon Rebalance",
        "trader": "Claude Shannon",
        "description": "Shannon's Demon—rebalance 50/50 to exploit volatility. Mean-reversion.",
        "ranging": {"sl": 1.5, "tp": 2.5},
        "trending": {"sl": 1.8, "tp": 3.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5–2×ATR. Exploit volatility through rebalancing. Buy dips, sell rips mechanically.",
    },
    "thorp": {
        "name": "Ed Thorp Kelly",
        "trader": "Ed Thorp",
        "description": "Kelly Criterion sizing. Mathematical edge. Never risk ruin.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR. Size by Kelly fraction (half-Kelly for safety). Never risk more than edge justifies.",
    },
    "aqr": {
        "name": "AQR Factor",
        "trader": "Cliff Asness / AQR",
        "description": "Multi-factor systematic. Value + momentum + carry. Academic rigor.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Multi-factor signals—momentum, value, carry. Diversify across factors.",
    },
    "two_sigma": {
        "name": "Two Sigma Systematic",
        "trader": "David Siegel / John Overdeck",
        "description": "ML-driven systematic. Data science approach. Ensemble signals.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5×ATR. Ensemble multiple signals. Data-driven, no single indicator dependency.",
    },
    "de_shaw": {
        "name": "D.E. Shaw Quant",
        "trader": "David Shaw",
        "description": "Computational finance pioneer. Statistical patterns in market microstructure.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.0},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.2–1.5×ATR. Exploit microstructure patterns. High frequency of small edges.",
    },
    "citadel": {
        "name": "Citadel Multi-Strat",
        "trader": "Ken Griffin",
        "description": "Multi-strategy. Market-making + stat arb + fundamental. Risk limits per book.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 1.8, "tp": 3.5},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5–2×ATR. Multi-strategy approach. Hard risk limits. Cut at drawdown threshold.",
    },
    "man_ahl": {
        "name": "Man AHL Systematic",
        "trader": "Man Group / AHL",
        "description": "CTA systematic trend + alternative signals. Decades of track record.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Systematic trend + alternative data. Trust the model over gut feeling.",
    },
    # ── VALUE / CONTRARIAN ─────────────────────────────────────────────────
    "buffett": {
        "name": "Buffett Value",
        "trader": "Warren Buffett",
        "description": "Margin of safety. Buy when others are fearful. Long-term conviction.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 5.5},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5–3×ATR (wide—conviction holds). Buy fear, sell greed. Margin of safety required.",
    },
    "icahn": {
        "name": "Carl Icahn Activist",
        "trader": "Carl Icahn",
        "description": "Activist contrarian. Buy undervalued, force change. Concentrated positions.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. Contrarian entries when asset is undervalued. Concentrated, high-conviction.",
    },
    "klarman": {
        "name": "Seth Klarman Value",
        "trader": "Seth Klarman",
        "description": "Deep value with margin of safety. Patient. Cash is a position.",
        "ranging": {"sl": 2.5, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5×ATR. Extreme patience. Cash is a valid position. Only enter with margin of safety.",
    },
    "marks": {
        "name": "Howard Marks Cycles",
        "trader": "Howard Marks",
        "description": "Cycle awareness. Buy when sentiment is extreme fear. Second-level thinking.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 2–2.5×ATR. Second-level thinking—what does the market NOT see? Buy extreme fear.",
    },
    "templeton": {
        "name": "Templeton Contrarian",
        "trader": "John Templeton",
        "description": "Maximum pessimism buying. Global contrarian. Buy when blood in streets.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 5.5},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2.5–3×ATR. Buy at point of maximum pessimism. Contrarian with wide stops.",
    },
    # ── MOMENTUM / GROWTH ──────────────────────────────────────────────────
    "driehaus": {
        "name": "Driehaus Momentum",
        "trader": "Richard Driehaus",
        "description": "Buy high, sell higher. Momentum investing pioneer. Ride the wave.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Buy strength, sell more strength. Momentum > value in crypto.",
    },
    "lynch": {
        "name": "Peter Lynch Growth",
        "trader": "Peter Lynch",
        "description": "Growth at reasonable price. Know what you own. Tenbaggers.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Understand the asset fundamentally. Hold winners for multi-X returns.",
    },
    "ryan": {
        "name": "David Ryan CANSLIM",
        "trader": "David Ryan",
        "description": "3x US Investing Champion. CANSLIM disciple. Tight stops, huge runners.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 1.8, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.2,
        "ai_guidance": "SL 1.5–2×ATR. Tight stops, let winners run 3–5×. Only buy leaders breaking out.",
    },
    # ── SHORT-TERM / SWING / DAY TRADING ───────────────────────────────────
    "raschke": {
        "name": "Raschke Short-Term",
        "trader": "Linda Raschke",
        "description": "Keltner-style (2.5 ATR). Cut losers quickly. ATR-based tools.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR. Keltner-style bands. Cut losers fast.",
    },
    "williams_balanced": {
        "name": "Williams Balanced",
        "trader": "Larry Williams",
        "description": "2× ATR industry standard. Balanced risk/reward.",
        "ranging": {"sl": 1.8, "tp": 3.0},
        "trending": {"sl": 2.0, "tp": 3.5},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR (industry standard). TP 1.5–2× SL.",
    },
    "williams_swing": {
        "name": "Williams Swing",
        "trader": "Larry Williams",
        "description": "3× ATR for volatile markets. Swing trading timeframe.",
        "ranging": {"sl": 2.5, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5–3×ATR for crypto volatility. TP 2× SL.",
    },
    "douglas": {
        "name": "Mark Douglas Zone",
        "trader": "Mark Douglas",
        "description": "Trading in the Zone psychology. Probabilistic thinking. No fear, no greed.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR. Think in probabilities. Every trade is independent. No revenge trading.",
    },
    "elder": {
        "name": "Alexander Elder",
        "trader": "Alexander Elder",
        "description": "Triple Screen system. Multi-timeframe. Impulse + momentum alignment.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR. Multi-timeframe confirmation required. Trade with the weekly, enter on daily.",
    },
    "neff": {
        "name": "John Neff Low P/E",
        "trader": "John Neff",
        "description": "Low P/E contrarian. Buy unloved, sell when loved. Windsor Fund legend.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Buy when sentiment is negative but fundamentals intact. Sell into euphoria.",
    },
    # ── VOLATILITY / OPTIONS-INSPIRED ──────────────────────────────────────
    "taleb": {
        "name": "Taleb Barbell",
        "trader": "Nassim Taleb",
        "description": "Barbell strategy. Small losses, huge tail gains. Antifragile positioning.",
        "ranging": {"sl": 1.0, "tp": 5.0},
        "trending": {"sl": 1.2, "tp": 6.0},
        "chaotic": {"sl": 1.5, "tp": 7.0},
        "min_rr": 3.0,
        "ai_guidance": "Tight SL 1–1.5×ATR. Massive TP 5–7×ATR. Accept many small losses for rare huge wins. Antifragile.",
    },
    "niederhoffer": {
        "name": "Niederhoffer Mean-Rev",
        "trader": "Victor Niederhoffer",
        "description": "Statistical mean-reversion. Buy panic, sell euphoria. Counting-based.",
        "ranging": {"sl": 1.5, "tp": 2.5},
        "trending": {"sl": 1.8, "tp": 3.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5–2×ATR. Mean-reversion—buy oversold, sell overbought. Statistical counting.",
    },
    # ── FIXED INCOME / BOND TRADER ADAPTED ─────────────────────────────────
    "gross": {
        "name": "Bill Gross Bond King",
        "trader": "Bill Gross",
        "description": "Macro rate cycle awareness. Secular trends. Patient positioning.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Macro rate cycle awareness. Position for secular trends, not noise.",
    },
    "gundlach": {
        "name": "Gundlach DoubleLine",
        "trader": "Jeffrey Gundlach",
        "description": "Contrarian macro. Chart-driven bond king. Calls major turns.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Chart-driven macro calls. Position for major turns, not minor swings.",
    },
    # ── CRYPTO-NATIVE LEGENDS ──────────────────────────────────────────────
    "crypto_swing": {
        "name": "Crypto Swing Pro",
        "trader": "Crypto best practices",
        "description": "2–3× ATR for 4h–1D. Accommodates crypto volatility.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2–3×ATR. Crypto needs room. Avoid whipsaws.",
    },
    "crypto_conservative": {
        "name": "Crypto Maximum Room",
        "trader": "High-volatility best practices",
        "description": "3× ATR+ stops. For extreme volatility. Fewer trades, wider stops.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 3.0, "tp": 6.0},
        "chaotic": {"sl": 3.5, "tp": 7.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5–3.5×ATR. Maximum breathing room. Reduce false stops.",
    },
    "saylor": {
        "name": "Saylor HODL Conviction",
        "trader": "Michael Saylor",
        "description": "Maximum conviction BTC accumulation. Wide stops, never sell the winner.",
        "ranging": {"sl": 3.0, "tp": 6.0},
        "trending": {"sl": 3.0, "tp": 7.0},
        "chaotic": {"sl": 3.5, "tp": 7.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 3×ATR (very wide). Conviction accumulation. Only buy, rarely sell. Diamond hands.",
    },
    "hayes": {
        "name": "Arthur Hayes Degen",
        "trader": "Arthur Hayes",
        "description": "BitMEX founder style. Macro + crypto native. Aggressive leveraged swings.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.0, "tp": 4.5},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Macro-driven crypto thesis. Aggressive when conviction is high. Cut fast otherwise.",
    },
    "su_zhu": {
        "name": "Su Zhu Supercycle",
        "trader": "Su Zhu (pre-3AC)",
        "description": "Crypto supercycle thesis. Ride major trends. High conviction, wide stops.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 6.0},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2.5×ATR. Ride the supercycle. Wide stops for crypto vol. WARNING: manage risk unlike 3AC.",
    },
    "cobie": {
        "name": "Cobie CT Alpha",
        "trader": "Cobie (Jordan Fish)",
        "description": "Crypto Twitter alpha. Narrative trading. Early conviction, staged exits.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Trade the narrative. Early entry, staged profit-taking. Don't marry your bags.",
    },
    "pentoshi": {
        "name": "Pentoshi Swing",
        "trader": "Pentoshi",
        "description": "Crypto swing trader. HTF bias + LTF entries. Patient, disciplined.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. HTF trend bias, LTF entry. Patient entries, let trades come to you.",
    },
    "hsaka": {
        "name": "Hsaka Scalp-Swing",
        "trader": "Hsaka",
        "description": "Crypto order flow + structure. Scalp to swing. Precision entries.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.5},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.2–1.5×ATR. Order flow + market structure. Precision entries at key levels.",
    },
    "ansem": {
        "name": "Ansem Degen Momentum",
        "trader": "Ansem",
        "description": "Crypto momentum + narrative. Ride memes and momentum. Fast in, fast out.",
        "ranging": {"sl": 1.2, "tp": 3.0},
        "trending": {"sl": 1.5, "tp": 4.0},
        "chaotic": {"sl": 1.8, "tp": 3.5},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.2–1.5×ATR. Momentum + narrative driven. Fast entries, trail stops aggressively.",
    },
    "gainzy": {
        "name": "GCR Contrarian",
        "trader": "GCR (Gigantic Rebirth)",
        "description": "Crypto contrarian. Fade the crowd. Short euphoria, buy despair.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.5},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. Contrarian—fade extreme sentiment. Short euphoria, buy capitulation.",
    },
    "light": {
        "name": "Light Crypto Macro",
        "trader": "Light (Crypto)",
        "description": "Macro-driven crypto. DXY, rates, liquidity flows. Institutional lens.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Macro-first crypto trading. DXY, rates, liquidity drive the thesis.",
    },
    # ── EMERGING MARKET / GLOBAL ───────────────────────────────────────────
    "mobius": {
        "name": "Mark Mobius EM",
        "trader": "Mark Mobius",
        "description": "Emerging market pioneer. High volatility tolerance. Long-term growth.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 5.5},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5–3×ATR. High volatility tolerance. Long-term growth thesis. Patient accumulation.",
    },
    "rogers": {
        "name": "Jim Rogers Commodities",
        "trader": "Jim Rogers",
        "description": "Commodity supercycles. Contrarian global macro. Buy what's cheap and hated.",
        "ranging": {"sl": 2.5, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5×ATR. Buy what's cheap and hated. Commodity cycle awareness. Extreme patience.",
    },
    # ── EVENT-DRIVEN / SPECIAL SITUATIONS ──────────────────────────────────
    "paulson": {
        "name": "John Paulson Event",
        "trader": "John Paulson",
        "description": "Event-driven. Asymmetric bets on macro dislocations. The Big Short.",
        "ranging": {"sl": 1.5, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.0, "tp": 6.0},
        "min_rr": 2.5,
        "ai_guidance": "SL 1.5–2×ATR. Asymmetric event bets. Small risk, huge payoff on dislocations.",
    },
    "tepper": {
        "name": "David Tepper Distressed",
        "trader": "David Tepper",
        "description": "Buy distressed when others panic. Appaloosa style. Aggressive in fear.",
        "ranging": {"sl": 2.0, "tp": 4.5},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 6.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. Buy distressed assets in panic. Aggressive when fear is maximum.",
    },
    "einhorn": {
        "name": "David Einhorn Value",
        "trader": "David Einhorn",
        "description": "Deep research value. Short frauds, long quality. Greenlight Capital.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Deep research conviction. Only trade when you know something the market doesn't.",
    },
    "loeb": {
        "name": "Dan Loeb Activist",
        "trader": "Daniel Loeb",
        "description": "Third Point activist. Event-driven + value. Catalyst-focused entries.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Catalyst-driven entries. Identify the event that unlocks value.",
    },
    "ackman": {
        "name": "Bill Ackman Conviction",
        "trader": "Bill Ackman",
        "description": "Concentrated conviction. Big bets on quality. Pershing Square style.",
        "ranging": {"sl": 2.0, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2–2.5×ATR. Concentrated high-conviction bets. Quality assets only. Hold through volatility.",
    },
    # ── TIGER CUBS / MODERN HEDGE FUNDS ────────────────────────────────────
    "coleman": {
        "name": "Chase Coleman Tiger",
        "trader": "Chase Coleman",
        "description": "Tiger Global style. Growth + tech conviction. Long-term compounders.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Growth conviction. Identify long-term compounders. Hold through drawdowns.",
    },
    "mandel": {
        "name": "Steve Mandel Lone Pine",
        "trader": "Steve Mandel",
        "description": "Lone Pine Capital. Fundamental long/short. Quality growth at scale.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Fundamental quality growth. Long the best, short the worst.",
    },
    "ainslie": {
        "name": "Lee Ainslie Maverick",
        "trader": "Lee Ainslie",
        "description": "Maverick Capital. Fundamental long/short equity. Tiger cub discipline.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Fundamental long/short. Pair trades to reduce market exposure.",
    },
    # ── MARKET WIZARDS / CLASSIC ───────────────────────────────────────────
    "marcus": {
        "name": "Michael Marcus",
        "trader": "Michael Marcus",
        "description": "Original Market Wizard. Macro + commodities. Mentor to Kovner.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2×ATR. Macro conviction trading. Cut losses, add to winners. Trust your analysis.",
    },
    "rogers_jim": {
        "name": "Jim Rogers Adventure",
        "trader": "Jim Rogers",
        "description": "Global macro adventurer. Quantum Fund co-founder. Contrarian commodity cycles.",
        "ranging": {"sl": 2.5, "tp": 4.5},
        "trending": {"sl": 2.5, "tp": 5.0},
        "chaotic": {"sl": 3.0, "tp": 5.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5×ATR. Global macro contrarian. Buy what nobody wants. Extreme patience.",
    },
    "schwartz": {
        "name": "Marty Schwartz Pit Bull",
        "trader": "Martin Schwartz",
        "description": "Pit Bull day trader. 9-period EMA. Cut losers instantly. Champion trader.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.5},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.2–1.5×ATR. Fast cuts. 9-EMA as guide. If below 9-EMA, get out.",
    },
    "jones_crt": {
        "name": "CRT Bond Arb",
        "trader": "Paul Tudor Jones (CRT era)",
        "description": "Early PTJ commodity/bond trading. Tape reading + macro. Aggressive sizing.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.8–2×ATR. Tape reading + macro. Aggressive when tape confirms. Cut immediately when wrong.",
    },
    # ── SYSTEMATIC MEAN-REVERSION ──────────────────────────────────────────
    "mean_rev_bollinger": {
        "name": "Bollinger Mean-Rev",
        "trader": "John Bollinger",
        "description": "Bollinger Band mean-reversion. Buy lower band, sell upper. Squeeze setups.",
        "ranging": {"sl": 1.5, "tp": 2.5},
        "trending": {"sl": 1.8, "tp": 3.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5–2×ATR. Mean-reversion at Bollinger extremes. Best in ranging markets.",
    },
    "mean_rev_connors": {
        "name": "Connors RSI Reversal",
        "trader": "Larry Connors",
        "description": "Short-term RSI mean-reversion. Buy RSI<10, sell RSI>90. High win rate.",
        "ranging": {"sl": 1.2, "tp": 2.0},
        "trending": {"sl": 1.5, "tp": 2.5},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.2,
        "ai_guidance": "SL 1.2–1.5×ATR. RSI extremes for mean-reversion. High win rate, small targets.",
    },
    # ── POSITION TRADING / LONG-TERM ───────────────────────────────────────
    "burry": {
        "name": "Michael Burry Deep Value",
        "trader": "Michael Burry",
        "description": "Deep value contrarian. The Big Short. Asymmetric bets on mispricing.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 6.0},
        "chaotic": {"sl": 3.0, "tp": 7.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 2.5–3×ATR. Deep value contrarian. Asymmetric mispricing bets. Patience is everything.",
    },
    "wood": {
        "name": "Cathie Wood Innovation",
        "trader": "Cathie Wood",
        "description": "Disruptive innovation conviction. 5-year time horizon. Buy the dip on innovation.",
        "ranging": {"sl": 2.5, "tp": 5.0},
        "trending": {"sl": 2.5, "tp": 6.0},
        "chaotic": {"sl": 3.0, "tp": 6.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 2.5–3×ATR. Innovation conviction. Wide stops for volatile assets. 5-year thesis.",
    },
    # ── SCALPING / HIGH FREQUENCY ADAPTED ──────────────────────────────────
    "scalp_tight": {
        "name": "Scalper Tight",
        "trader": "Professional scalpers",
        "description": "Ultra-tight stops. High win rate. Small targets. Volume-based entries.",
        "ranging": {"sl": 0.8, "tp": 1.5},
        "trending": {"sl": 1.0, "tp": 2.0},
        "chaotic": {"sl": 1.2, "tp": 2.0},
        "min_rr": 1.2,
        "ai_guidance": "SL 0.8–1×ATR. Ultra-tight. High frequency, small targets. Only at key levels.",
    },
    "scalp_momentum": {
        "name": "Momentum Scalp",
        "trader": "Crypto scalpers",
        "description": "Momentum scalping. Ride short bursts. Trail stops aggressively.",
        "ranging": {"sl": 1.0, "tp": 2.0},
        "trending": {"sl": 1.2, "tp": 3.0},
        "chaotic": {"sl": 1.5, "tp": 2.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1–1.2×ATR. Momentum bursts. Trail stop to breakeven fast. Quick profits.",
    },
    # ── RISK PARITY / PORTFOLIO ────────────────────────────────────────────
    "risk_parity": {
        "name": "Risk Parity",
        "trader": "Bridgewater / Risk Parity",
        "description": "Equal risk allocation. Volatility-weighted. Regime-adaptive sizing.",
        "ranging": {"sl": 2.0, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 2×ATR. Volatility-weighted sizing. Reduce in high vol, increase in low vol.",
    },
    # ── FIBONACCI / HARMONIC ───────────────────────────────────────────────
    "fib_trader": {
        "name": "Fibonacci Precision",
        "trader": "Harmonic traders",
        "description": "Fibonacci retracement entries. 0.618/0.786 levels. Harmonic patterns.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 1.8, "tp": 4.0},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.5–2×ATR below Fib level. Enter at 0.618/0.786 retracements. TP at extensions.",
    },
    # ── ICHIMOKU / ASIAN STYLE ─────────────────────────────────────────────
    "ichimoku": {
        "name": "Ichimoku Cloud",
        "trader": "Goichi Hosoda",
        "description": "Ichimoku Kinko Hyo. Cloud support/resistance. Multi-signal confirmation.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR below cloud. Trade with cloud direction. All 5 lines must confirm.",
    },
    # ── WYCKOFF / VOLUME PROFILE ───────────────────────────────────────────
    "wyckoff": {
        "name": "Wyckoff Method",
        "trader": "Richard Wyckoff",
        "description": "Accumulation/distribution phases. Spring/upthrust entries. Volume confirms.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR. Wyckoff phases—buy springs in accumulation, sell upthrusts in distribution.",
    },
    "volume_profile": {
        "name": "Volume Profile",
        "trader": "Market Profile traders",
        "description": "Value area + POC trading. Buy below value, sell above. Auction theory.",
        "ranging": {"sl": 1.5, "tp": 3.0},
        "trending": {"sl": 1.8, "tp": 3.5},
        "chaotic": {"sl": 2.0, "tp": 3.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5–2×ATR. Trade value area edges. Buy below POC, sell above. Auction market theory.",
    },
    # ── ELLIOTT WAVE ───────────────────────────────────────────────────────
    "elliott": {
        "name": "Elliott Wave",
        "trader": "R.N. Elliott / Prechter",
        "description": "Wave counting. Enter Wave 3/5, exit at completion. Fibonacci targets.",
        "ranging": {"sl": 1.8, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.8–2×ATR below wave origin. Target Wave 3 extensions (1.618×). Invalidation = wave count broken.",
    },
    # ── GAP / OPENING RANGE ────────────────────────────────────────────────
    "gap_trader": {
        "name": "Gap & Go",
        "trader": "Opening range traders",
        "description": "Trade opening gaps. Fade or follow. First 30-min range breakout.",
        "ranging": {"sl": 1.0, "tp": 2.0},
        "trending": {"sl": 1.2, "tp": 2.5},
        "chaotic": {"sl": 1.5, "tp": 2.5},
        "min_rr": 1.5,
        "ai_guidance": "SL 1–1.2×ATR. Trade opening range breakouts. First 30-min high/low as reference.",
    },
    # ── PAIRS / RELATIVE VALUE ─────────────────────────────────────────────
    "pairs_trade": {
        "name": "Pairs Trading",
        "trader": "Stat arb / relative value",
        "description": "Relative value. Long strong, short weak. Market-neutral approach.",
        "ranging": {"sl": 1.5, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.0},
        "chaotic": {"sl": 2.0, "tp": 3.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.5×ATR on spread. Relative value—long outperformer, short underperformer. Market-neutral.",
    },
    # ── VOLATILITY BREAKOUT ────────────────────────────────────────────────
    "vol_breakout": {
        "name": "Volatility Breakout",
        "trader": "Toby Crabel / NR7",
        "description": "NR7/inside bar breakouts. Low vol precedes high vol. Explosive moves.",
        "ranging": {"sl": 1.2, "tp": 3.0},
        "trending": {"sl": 1.5, "tp": 4.0},
        "chaotic": {"sl": 1.8, "tp": 3.5},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.2–1.5×ATR. Enter on volatility contraction breakouts (NR7, inside bars). Explosive follow-through.",
    },
    # ── GRID / DCA ─────────────────────────────────────────────────────────
    "grid_dca": {
        "name": "Grid DCA",
        "trader": "Systematic DCA",
        "description": "Dollar-cost averaging grid. Buy dips at intervals. Accumulation strategy.",
        "ranging": {"sl": 3.0, "tp": 4.0},
        "trending": {"sl": 3.0, "tp": 5.0},
        "chaotic": {"sl": 3.5, "tp": 5.0},
        "min_rr": 1.2,
        "ai_guidance": "SL 3×ATR (very wide). DCA into positions at grid levels. Accumulate, don't time perfectly.",
    },
    # ── SUPPLY & DEMAND / SMC ──────────────────────────────────────────────
    "smc": {
        "name": "Smart Money Concepts",
        "trader": "ICT / SMC traders",
        "description": "Order blocks, fair value gaps, liquidity sweeps. Institutional footprints.",
        "ranging": {"sl": 1.5, "tp": 3.5},
        "trending": {"sl": 1.8, "tp": 4.5},
        "chaotic": {"sl": 2.0, "tp": 4.0},
        "min_rr": 2.0,
        "ai_guidance": "SL 1.5–2×ATR below order block. Trade FVGs and liquidity sweeps. Follow smart money footprints.",
    },
    # ── RENAISSANCE / BLACK BOX ────────────────────────────────────────────
    "blackbox": {
        "name": "Black Box Quant",
        "trader": "Quantitative firms",
        "description": "Pure systematic. No discretion. Signal ensemble. Risk-managed.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.0},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.2–1.5×ATR. Pure systematic—no discretionary overrides. Trust the signal ensemble.",
    },
    # ── ANTI-FRAGILE / TAIL RISK ───────────────────────────────────────────
    "tail_risk": {
        "name": "Tail Risk Hunter",
        "trader": "Universa / Spitznagel",
        "description": "Mark Spitznagel style. Tiny risk, massive tail payoff. Black swan hunter.",
        "ranging": {"sl": 0.8, "tp": 5.0},
        "trending": {"sl": 1.0, "tp": 6.0},
        "chaotic": {"sl": 1.0, "tp": 8.0},
        "min_rr": 4.0,
        "ai_guidance": "SL 0.8–1×ATR (tiny). TP 5–8×ATR (massive). Accept 80% small losses for 20% huge wins. Tail risk.",
    },
    # ── MARKET MAKING / SPREAD ─────────────────────────────────────────────
    "market_maker": {
        "name": "Market Maker Spread",
        "trader": "Market makers",
        "description": "Tight spread capture. High frequency. Small edge, many trades.",
        "ranging": {"sl": 0.8, "tp": 1.5},
        "trending": {"sl": 1.0, "tp": 2.0},
        "chaotic": {"sl": 1.2, "tp": 2.0},
        "min_rr": 1.2,
        "ai_guidance": "SL 0.8–1×ATR. Tight spreads. High frequency, small edge. Avoid trending markets.",
    },
    # ── SEASONAL / CALENDAR ────────────────────────────────────────────────
    "seasonal": {
        "name": "Seasonal Patterns",
        "trader": "Seasonal traders",
        "description": "Calendar-based patterns. BTC halving cycles. Monthly/weekly seasonality.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 5.0},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Trade seasonal patterns—halving cycles, monthly seasonality. Align with calendar edge.",
    },
    # ── SENTIMENT / FEAR-GREED ─────────────────────────────────────────────
    "sentiment": {
        "name": "Sentiment Extremes",
        "trader": "Sentiment traders",
        "description": "Fear & Greed index driven. Buy extreme fear, sell extreme greed.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Trade sentiment extremes only. Buy Fear<20, sell Greed>80. Patience between signals.",
    },
    # ── VWAP / INSTITUTIONAL ───────────────────────────────────────────────
    "vwap": {
        "name": "VWAP Institutional",
        "trader": "Institutional traders",
        "description": "VWAP as fair value. Buy below VWAP, sell above. Institutional benchmark.",
        "ranging": {"sl": 1.2, "tp": 2.5},
        "trending": {"sl": 1.5, "tp": 3.0},
        "chaotic": {"sl": 1.8, "tp": 3.0},
        "min_rr": 1.5,
        "ai_guidance": "SL 1.2–1.5×ATR. VWAP as fair value anchor. Buy below, sell above. Institutional flow.",
    },
    # ── BREAKOUT / DONCHIAN ────────────────────────────────────────────────
    "donchian": {
        "name": "Donchian Channel",
        "trader": "Richard Donchian",
        "description": "Father of trend following. 20-day breakout. Simple, mechanical, effective.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. Buy 20-period high breakout. Sell 10-period low. Mechanical trend following.",
    },
    # ── GANN / TIME-PRICE ──────────────────────────────────────────────────
    "gann": {
        "name": "W.D. Gann Geometric",
        "trader": "W.D. Gann",
        "description": "Time-price geometry. Gann angles and squares. Cyclical analysis.",
        "ranging": {"sl": 1.8, "tp": 3.5},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 4.5},
        "min_rr": 1.8,
        "ai_guidance": "SL 1.8–2×ATR. Time-price geometry. Gann angles for support/resistance. Cyclical timing.",
    },
    # ── POINT & FIGURE ─────────────────────────────────────────────────────
    "pnf": {
        "name": "Point & Figure",
        "trader": "P&F chartists",
        "description": "Noise-filtered price action. Box reversal signals. Clear targets.",
        "ranging": {"sl": 2.0, "tp": 4.0},
        "trending": {"sl": 2.0, "tp": 4.5},
        "chaotic": {"sl": 2.5, "tp": 5.0},
        "min_rr": 1.8,
        "ai_guidance": "SL 2×ATR. P&F filtered signals—ignore noise. Trade double-top breakouts, double-bottom breakdowns.",
    },
}


def get_preset(preset_id: str | None) -> dict:
    """Return preset config. Falls back to 'turtle' if invalid."""
    pid = (preset_id or "").strip().lower() or "turtle"
    return PRESETS.get(pid, PRESETS["turtle"])


def get_sl_tp_for_regime(preset_id: str | None, regime: str) -> tuple[float, float]:
    """Return (min_sl_atr, min_tp_atr) for the given preset and regime."""
    p = get_preset(preset_id)
    regime = (regime or "ranging").lower()
    if regime == "chaotic":
        r = p["chaotic"]
    elif regime in ("trending_up", "trending_down"):
        r = p["trending"]
    else:
        r = p["ranging"]
    return r["sl"], r["tp"]


def get_min_rr(preset_id: str | None) -> float:
    """Return minimum R:R for the preset."""
    return float(get_preset(preset_id).get("min_rr", 1.5))


PRESET_CATEGORIES = {
    "default": "General",
    "turtle": "Trend Following",
    "seykota": "Trend Following",
    "trend_dunn": "Trend Following",
    "trend_henry": "Trend Following",
    "trend_harding": "Trend Following",
    "trend_abraham": "Trend Following",
    "trend_millburn": "Trend Following",
    "donchian": "Trend Following",
    "soros": "Macro",
    "ptj": "Macro",
    "druckenmiller": "Macro",
    "kovner": "Macro",
    "bacon": "Macro",
    "dalio": "Macro",
    "robertson": "Macro",
    "steinhardt": "Macro",
    "tudor_bvi": "Macro",
    "gross": "Macro",
    "gundlach": "Macro",
    "livermore": "Stock Legends",
    "minervini": "Stock Legends",
    "oneil": "Stock Legends",
    "darvas": "Stock Legends",
    "zanger": "Stock Legends",
    "weinstein": "Stock Legends",
    "lefevre": "Stock Legends",
    "simons": "Quantitative",
    "shannon": "Quantitative",
    "thorp": "Quantitative",
    "aqr": "Quantitative",
    "two_sigma": "Quantitative",
    "de_shaw": "Quantitative",
    "citadel": "Quantitative",
    "man_ahl": "Quantitative",
    "blackbox": "Quantitative",
    "buffett": "Value / Contrarian",
    "icahn": "Value / Contrarian",
    "klarman": "Value / Contrarian",
    "marks": "Value / Contrarian",
    "templeton": "Value / Contrarian",
    "neff": "Value / Contrarian",
    "burry": "Value / Contrarian",
    "driehaus": "Momentum / Growth",
    "lynch": "Momentum / Growth",
    "ryan": "Momentum / Growth",
    "wood": "Momentum / Growth",
    "raschke": "Short-Term / Swing",
    "williams_balanced": "Short-Term / Swing",
    "williams_swing": "Short-Term / Swing",
    "douglas": "Short-Term / Swing",
    "elder": "Short-Term / Swing",
    "schwartz": "Short-Term / Swing",
    "jones_crt": "Short-Term / Swing",
    "taleb": "Volatility / Tail Risk",
    "niederhoffer": "Volatility / Tail Risk",
    "tail_risk": "Volatility / Tail Risk",
    "vol_breakout": "Volatility / Tail Risk",
    "crypto_swing": "Crypto Native",
    "crypto_conservative": "Crypto Native",
    "saylor": "Crypto Native",
    "hayes": "Crypto Native",
    "su_zhu": "Crypto Native",
    "cobie": "Crypto Native",
    "pentoshi": "Crypto Native",
    "hsaka": "Crypto Native",
    "ansem": "Crypto Native",
    "gainzy": "Crypto Native",
    "light": "Crypto Native",
    "mobius": "Global / Emerging",
    "rogers": "Global / Emerging",
    "rogers_jim": "Global / Emerging",
    "paulson": "Event-Driven",
    "tepper": "Event-Driven",
    "einhorn": "Event-Driven",
    "loeb": "Event-Driven",
    "ackman": "Event-Driven",
    "coleman": "Tiger Cubs / Modern HF",
    "mandel": "Tiger Cubs / Modern HF",
    "ainslie": "Tiger Cubs / Modern HF",
    "marcus": "Market Wizards Classic",
    "mean_rev_bollinger": "Mean-Reversion",
    "mean_rev_connors": "Mean-Reversion",
    "scalp_tight": "Scalping",
    "scalp_momentum": "Scalping",
    "market_maker": "Scalping",
    "risk_parity": "Portfolio / Systematic",
    "fib_trader": "Technical Systems",
    "ichimoku": "Technical Systems",
    "wyckoff": "Technical Systems",
    "volume_profile": "Technical Systems",
    "elliott": "Technical Systems",
    "gann": "Technical Systems",
    "pnf": "Technical Systems",
    "smc": "Technical Systems",
    "gap_trader": "Technical Systems",
    "vwap": "Technical Systems",
    "pairs_trade": "Technical Systems",
    "grid_dca": "Portfolio / Systematic",
    "seasonal": "Portfolio / Systematic",
    "sentiment": "Portfolio / Systematic",
}

CATEGORY_ORDER = [
    "General",
    "Trend Following",
    "Macro",
    "Stock Legends",
    "Quantitative",
    "Value / Contrarian",
    "Momentum / Growth",
    "Short-Term / Swing",
    "Volatility / Tail Risk",
    "Crypto Native",
    "Global / Emerging",
    "Event-Driven",
    "Tiger Cubs / Modern HF",
    "Market Wizards Classic",
    "Mean-Reversion",
    "Scalping",
    "Portfolio / Systematic",
    "Technical Systems",
]


def list_presets() -> list[dict]:
    """Return all presets for UI selection, grouped by category."""
    return [
        {
            "id": k,
            "name": v["name"],
            "trader": v["trader"],
            "description": v["description"],
            "category": PRESET_CATEGORIES.get(k, "General"),
        }
        for k, v in PRESETS.items()
    ]


def list_preset_categories() -> list[str]:
    """Return ordered category list for UI grouping."""
    return list(CATEGORY_ORDER)
